stages:
  - deploy

deploy_production:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache lftp
  script:
    - lftp -c "set sftp:auto-confirm yes;
               open -u $SFTP_USER,$SFTP_PASSWORD sftp://$SFTP_HOST;
               mirror -R --verbose
                 --exclude-glob .git*
                 --exclude-glob .gitlab-ci.yml
                 --exclude-glob README.md
                 ./tmisura.sk/sub/Portfoliotracker/"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'